import React,{useEffect,useMemo,useState} from 'react';
import {Client} from '@stomp/stompjs';
import {Area,AreaChart,CartesianGrid,ResponsiveContainer,Tooltip,XAxis,YAxis} from 'recharts';
const API=import.meta.env.VITE_API_URL||'http://localhost:8080';
function App(){
 const [auth,setAuth]=useState(()=>sessionStorage.getItem('pw-auth')||'');const [services,setServices]=useState([]);const [summary,setSummary]=useState({});const [alerts,setAlerts]=useState([]);const [incidents,setIncidents]=useState([]);const [events,setEvents]=useState([]);const [selected,setSelected]=useState(null);const [metrics,setMetrics]=useState([]);const [error,setError]=useState('');
 async function api(path,options={}){const res=await fetch(`${API}${path}`,{...options,headers:{'Content-Type':'application/json',...(auth?{Authorization:`Basic ${auth}`} :{}),...options.headers}});if(!res.ok)throw Error(`${res.status} ${res.statusText}`);return res.status===204?null:res.json();}
 async function refresh(){try{const [s,d,a,i]=await Promise.all([api('/api/services'),api('/api/dashboard/summary'),api('/api/alerts'),api('/api/incidents')]);setServices(s);setSelected(current=>current?s.find(x=>x.id===current.id)||current:null);setSummary(d);setAlerts(a);setIncidents(i);setError('');if(selected){const m=await api(`/api/services/${selected.id}/metrics`);setMetrics([...(m.history||[])].reverse().map(x=>({time:new Date(x.recordedAt).toLocaleTimeString(),latency:x.averageLatencyMs,error:x.errorRate})));}}catch(e){setError(e.message.includes('401')?'Sign in with your PulseWatch admin credentials.':e.message);}}
 useEffect(()=>{if(!auth)return;refresh();const timer=setInterval(refresh,15000);const client=new Client({brokerURL:API.replace(/^http/,'ws')+'/ws',reconnectDelay:3000,onConnect:()=>client.subscribe('/topic/events',msg=>{const item=JSON.parse(msg.body);setEvents(old=>[item,...old].slice(0,30));refresh();})});client.activate();return()=>{clearInterval(timer);client.deactivate();};},[auth,selected?.id]);
 async function login(e){e.preventDefault();const f=new FormData(e.currentTarget);const value=btoa(`${f.get('user')}:${f.get('pass')}`);sessionStorage.setItem('pw-auth',value);setAuth(value);}
 async function changeAlert(id,action){await api(`/api/alerts/${id}/${action}`,{method:'PUT'});refresh();}
 const cards=[['Services',summary.totalServices??0,'bi-grid'],['Healthy',summary.up??0,'bi-check-circle'],['Degraded',summary.degraded??0,'bi-exclamation-triangle'],['Down',summary.down??0,'bi-x-circle'],['Active alerts',summary.activeAlerts??0,'bi-bell'],['Critical',summary.criticalAlerts??0,'bi-lightning'],['Open incidents',summary.openIncidents??0,'bi-fire'],['Avg latency',`${Math.round(summary.averageLatencyMs||0)} ms`,'bi-speedometer2']];
 if(!auth)return <main className="login"><div className="login-card"><div className="brand-mark">P</div><h1>PulseWatch</h1><p>Operations console · sign in to continue</p><form onSubmit={login}><label className="form-label">Username</label><input className="form-control mb-3" name="user" defaultValue="admin" required/><label className="form-label">Password</label><input className="form-control mb-3" type="password" name="pass" required/><button className="btn btn-primary w-100">Sign in</button></form><small>Configure admin credentials with ADMIN_USERNAME and ADMIN_PASSWORD.</small></div></main>;
 return <div className="shell"><aside className="sidebar"><div className="brand"><span className="brand-mark">P</span><span>PulseWatch</span></div><div className="side-caption">MONITORING</div><div className="side-link active">▦ &nbsp; Overview</div><div className="side-link">◉ &nbsp; Services</div><div className="side-link">⚑ &nbsp; Incidents</div><div className="side-caption mt-4">SYSTEM</div><div className="side-link">◌ &nbsp; Settings</div><div className="sidebar-foot"><span className="live-dot"/> Collector online</div></aside>
 <main className="content"><header className="topbar"><div><div className="eyebrow">OPERATIONS / OVERVIEW</div><h2>System overview</h2><p>Live health across your monitored services</p></div><div className="top-actions"><span className="live-pill"><i/> LIVE</span><button className="btn btn-sm btn-outline-light" onClick={()=>{sessionStorage.removeItem('pw-auth');setAuth('');}}>Sign out</button><button className="btn btn-sm btn-primary" onClick={refresh}>↻ Refresh</button></div></header>
 {error&&<div className="alert alert-warning">API connection: {error}</div>}<section className="stats">{cards.map(([name,value,icon])=><article className="stat" key={name}><div className="stat-label">{name}<span>{icon.slice(3,4)}</span></div><strong>{value}</strong><small>{name==='Services'?'registered targets':name==='Avg latency'?'latest observed':'current state'}</small></article>)}</section>
 <section className="grid-main"><article className="panel service-panel"><div className="panel-head"><div><h3>Service health</h3><p>Current state of registered services</p></div><span className="count-chip">{services.length} SERVICES</span></div>{services.length===0?<div className="empty">No services registered yet. Create one through <code>POST /api/services</code>.</div>:<div className="service-list">{services.map(s=><button className={`service-row ${selected?.id===s.id?'selected':''}`} key={s.id} onClick={()=>setSelected(s)}><span className={`state-dot ${s.status==='UP'?'up':s.status==='DOWN'?'down':s.status==='DEGRADED'?'degraded':'unknown'}`}/><span className="service-name"><b>{s.name}</b><small>{s.environment} · {s.host}:{s.port} · {s.lastCheckedAt?new Date(s.lastCheckedAt).toLocaleTimeString():'never checked'}</small></span><span className="service-state">{s.enabled?`${s.status}${s.responseTimeMs==null?'':` · ${s.responseTimeMs} ms`}`:'Disabled'}</span><span className="chevron">›</span></button>)}</div>}</article>
 <article className="panel event-panel"><div className="panel-head"><div><h3>Live activity</h3><p>Monitoring events as they happen</p></div><span className="live-dot"/></div>{events.length===0?<div className="empty">Waiting for monitoring events…</div>:events.map((e,n)=><div className="event-row" key={n}><span className="event-icon">⚡</span><div><b>{e.type.replaceAll('_',' ')}</b><small>{new Date().toLocaleTimeString()}</small></div></div>)}</article></section>
 <section className="grid-bottom"><article className="panel chart-panel"><div className="panel-head"><div><h3>{selected?`${selected.name} · latency`:'Latency trend'}</h3><p>Recorded health checks · milliseconds</p></div>{selected&&<button className="btn btn-sm btn-outline-light" onClick={()=>setSelected(null)}>All services</button>}</div>{metrics.length?<ResponsiveContainer width="100%" height={210}><AreaChart data={metrics}><defs><linearGradient id="latency" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#5b8cff" stopOpacity={.3}/><stop offset="100%" stopColor="#5b8cff" stopOpacity={0}/></linearGradient></defs><CartesianGrid stroke="#202b3b" vertical={false}/><XAxis dataKey="time" stroke="#69778a"/><YAxis stroke="#69778a"/><Tooltip contentStyle={{background:'#111b29',border:'1px solid #26364a',borderRadius:8}}/><Area dataKey="latency" stroke="#6e9aff" fill="url(#latency)" strokeWidth={2}/></AreaChart></ResponsiveContainer>:<div className="empty">{selected?'No measurements yet. The collector will populate this chart after its first check.':'Select a service to view its measured latency history.'}</div>}</article>
 <article className="panel alert-panel"><div className="panel-head"><div><h3>Active alerts</h3><p>Investigate and acknowledge</p></div><span className="count-chip danger">{alerts.filter(a=>a.status!=='RESOLVED').length} OPEN</span></div>{alerts.filter(a=>a.status!=='RESOLVED').slice(0,5).map(a=><div className="alert-row" key={a.id}><span className={`severity ${a.severity.toLowerCase()}`}/><div className="alert-copy"><b>{a.service?.name||'Service'} · {a.severity}</b><small>{a.message}</small></div>{a.status==='OPEN'&&<button className="ack" onClick={()=>changeAlert(a.id,'acknowledge')}>Ack</button>}<button className="ack" onClick={()=>changeAlert(a.id,'resolve')}>Resolve</button></div>)}{!alerts.some(a=>a.status!=='RESOLVED')&&<div className="empty">No active alerts</div>}</article></section>
 <section className="panel incidents"><div className="panel-head"><div><h3>Incidents</h3><p>Critical events requiring attention</p></div><span className="count-chip">{incidents.length} TOTAL</span></div>{incidents.length?incidents.slice(0,5).map(i=><div className="incident-row" key={i.id}><span className="severity critical"/><b>{i.service?.name||'Service'} incident</b><span>{i.alert?.message}</span><small>{new Date(i.createdAt).toLocaleString()}</small></div>):<div className="empty">No incidents have been triggered.</div>}</section>
 <footer>PulseWatch <span>Monitoring data comes from real HTTP health checks.</span><a href={`${API}/actuator/health`} target="_blank">API health ↗</a></footer></main></div>;
}
export default App;
